### ISSUE TITLE
Uploaders needs updating in d.control

### ISSUE THREAD

**Issue by ghost** [Linaro/pkg-django-testproject#5]
Please remove me (codehelp@debian.org) from the Uploaders field and replace with current team members.

**Comment by terceiro** [comment]
hello @codehelp!

I don't think this package is being used at all, so I just requested it to be removed from Debian entirely:

https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=1037499

**Comment by terceiro** [comment]
the package has been removed from unstable and testing
